net_width: 256
multi_speaker: False
max_seq_len: 1000

encoder:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 256
  encoder_dropout: 0.2
  
decoder:
  decoder_layer: 6
  decoder_head: 2
  decoder_hidden: 256
  decoder_dropout: 0.2
  
fftblock:
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  
variance_predictor:
  filter_n: 256
  kernel_size: 3
  dropout: 0.5

variance_embedding:
  n_bins: 256